### PR TITLE
improve README.md

### PR DESCRIPTION
**Pull request by josmardias**
* Compatibility notice should be on the top, users need to know it ASAP
* Remove "for Node.js" because it does not use Node.js API, so it's an universal/isomorphic package
* Add transpilation information to the compatibility notice

### CODE REVIEW

**Comment by josmardias** [comment]
Some people tries libs without reading all of the README.md and docs.

For example, [this guy](https://forums.meteor.com/t/npm-modules-using-strict-mode-not-working-in-meteor-1-3/19790?u=josmardias) tried this package on Meteor, that uses Node.js v0.10.x

**Comment by josmardias** [comment]
@brycebaril 
Can you take a look on this PR please? :blush:

**Comment by brycebaril** [comment]
Hi @josmardias this got buried in my inbox, just got to it now. I decided to relent in a different way and switched back to using `var` vs `const`/`let` and published that as v2.0.2.

Would still like to get your docs change in minus the two compatibility notices though, mind reworking it so that it just has the change for universal/isomorphic users?

**Comment by josmardias** [comment]
I had to create [another PR](https://github.com/brycebaril/node-stats-lite/pull/5) because I removed the repository.

**Pull request closed without merging**
